name: Docker Sync Hedwi Mail

on:
#  push:
#    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: '0 21 * * *'

jobs:
  sync_hedwi_task:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "latest"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync hedwi-task:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: hedwi/hedwi-task:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/hedwi/hedwi-task:${{ matrix.version }}
  


  sync_hedwi_search:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "latest"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync hedwi-search:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: hedwi/hedwi-search:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/hedwi/hedwi-search:${{ matrix.version }}
  
  sync_hedwi_hub:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "latest"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync hedwi-hub:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: hedwi/hedwi-hub:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/hedwi/hedwi-hub:${{ matrix.version }}
  


  sync_hedwi_imap:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "latest"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync hedwi-imap:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: hedwi/hedwi-imap:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/hedwi/hedwi-imap:${{ matrix.version }}
  
  sync_hedwi_filter:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "latest"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync hedwi-filter:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: hedwi/hedwi-filter:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/hedwi/hedwi-filter:${{ matrix.version }}
  


  sync_hedwi_smtp:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "latest"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync hedwi-smtp:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: hedwi/hedwi-smtp:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/hedwi/hedwi-smtp:${{ matrix.version }}
  
 

