name: Docker Sync Hedwi inbox

on:
#  push:
#    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: '0 21 * * 5'

jobs:
  sync_hedwi_inbox:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "latest"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync hedwi-inbox:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: hedwi/hedwi-inbox:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/hedwi/hedwi-inbox:${{ matrix.version }}



  sync_hedwi_office_api:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "latest"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync hedwi-office-api:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: hedwi/hedwi-office-api:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/hedwi/hedwi-office-api:${{ matrix.version }}
  
