name: Docker Sync

on:
  push:
    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:
  sync_nginx:

    runs-on: ubuntu-latest

    steps:
      - name: Login to Ali
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: Sync NGINX Stable
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/nginx:stable
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/suyar/nginx:stable

      - name: Sync NGINX Latest
        uses: docker/build-push-action@v2
        with:
          src: docker.io/nginx:latest
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/suyar/nginx:latest
