name: Docker Sync Deps

on:
#  push:
#    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: '0 21 * * 5'

jobs:

  sync_consul:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "1.18"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync hedwi-consul:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: hedwi/consul:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/hedwi/consul:${{ matrix.version }}
  
  sync_minio:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "RELEASE.2024-06-11T03-13-30Z"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync minio:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: hedwi/minio:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/hedwi/minio:${{ matrix.version }}
  


  sync_cockroach:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "v23.2.5"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync cockroach:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: hedwi/cockroach:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/hedwi/cockroach:${{ matrix.version }}
  
  sync_redis:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "6.0"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync redis:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: hedwi/redis:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/hedwi/redis:${{ matrix.version }}
  


  sync_nats:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "2.9.25"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync nats:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: hedwi/nats:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/hedwi/nats:${{ matrix.version }}

  sync_hedwi_mqtt:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "latest"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync hedwi-mqtt:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: hedwi/hedwi-mqtt:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/hedwi/hedwi-mqtt:${{ matrix.version }}

  
  sync_nginx:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "1.22"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync nginx:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: hedwi/nginx:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/hedwi/nginx:${{ matrix.version }}
