name: Docker Sync Library

on:
  push:
    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: '0 17 * * *'

jobs:
  sync_nginx:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "latest"
          - "stable"
          - "alpine"
          - "stable-alpine"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync nginx:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/library/nginx:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/nginx:${{ matrix.version }}

  sync_mysql:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "latest"
          - "8"
          - "8.0"
          - "5"
          - "5.7"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync mysql:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/library/mysql:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/mysql:${{ matrix.version }}

  sync_redis:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "latest"
          - "5"
          - "6"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync redis:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/library/redis:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/redis:${{ matrix.version }}

  sync_php:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync php:${{ matrix.version }}-cli
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/library/php:${{ matrix.version }}-cli
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:${{ matrix.version }}-cli

      - name: sync php:${{ matrix.version }}-fpm
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/library/php:${{ matrix.version }}-fpm
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:${{ matrix.version }}-fpm

      - name: sync php:${{ matrix.version }}-cli-alpine
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/library/php:${{ matrix.version }}-cli-alpine
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:${{ matrix.version }}-cli-alpine

      - name: sync php:${{ matrix.version }}-fpm-alpine
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/library/php:${{ matrix.version }}-fpm-alpine
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:${{ matrix.version }}-fpm-alpine
