name: Docker Sync

on:
  push:
    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: '0 16 * * *'

jobs:
  sync_nginx:

    runs-on: ubuntu-latest

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync nginx:latest
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/nginx:latest
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/nginx:latest

      - name: sync nginx:stable
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/nginx:stable
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/nginx:stable

  sync_mysql:

    runs-on: ubuntu-latest

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync mysql:latest
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/mysql:latest
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/mysql:latest

      - name: sync mysql:8
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/mysql:8
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/mysql:8

      - name: sync mysql:8.0
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/mysql:8.0
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/mysql:8.0

      - name: sync mysql:5
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/mysql:5.7
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/mysql:5
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/mysql:5.7

  sync_redis:

    runs-on: ubuntu-latest

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync redis:latest
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/redis:latest
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/redis:latest

      - name: sync redis:5
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/redis:5
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/redis:5

      - name: sync redis:6
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/redis:6
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/redis:6

  sync_php:

    runs-on: ubuntu-latest

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync php:8.1-cli
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/php:8.1-cli
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:8.1-cli

      - name: sync php:8.1-fpm
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/php:8.1-fpm
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:8.1-fpm

      - name: sync php:8.0-cli
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/php:8.0-cli
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:8.0-cli

      - name: sync php:8.0-fpm
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/php:8.0-fpm
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:8.0-fpm

      - name: sync php:7.4-cli
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/php:7.4-cli
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:7.4-cli

      - name: sync php:7.4-fpm
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/php:7.4-fpm
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:7.4-fpm

      - name: sync php:7.3-cli
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/php:7.3-cli
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:7.3-cli

      - name: sync php:7.3-fpm
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/php:7.3-fpm
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:7.3-fpm

      - name: sync php:7.2-cli
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/php:7.2-cli
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:7.2-cli

      - name: sync php:7.2-fpm
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/php:7.2-fpm
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:7.2-fpm

      - name: sync php:7.1-cli
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/php:7.1-cli
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:7.1-cli

      - name: sync php:7.1-fpm
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/php:7.1-fpm
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:7.1-fpm

      - name: sync php:7.0-cli
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/php:7.0-cli
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:7.0-cli

      - name: sync php:7.0-fpm
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/php:7.0-fpm
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:7.0-fpm
